export enum DialogNodeOptionRule {
    gold = 'gold',
    level = 'level',
    levelBelow = 'levelBelow',
    brotherhood = 'brotherhood',
    items = 'items',
    percentageChance = 'percentageChance',
    questStep = 'questStep',
    questBeforeStep = 'questBeforeStep',
    questAfterStep = 'questAfterStep',
    dragonTears = 'dragonTears',
    messageContent = 'messageContent',
    dialogCounter = 'dialogCounter',
    seasonalEvent = 'seasonalEvent',
    timeAfter = 'timeAfter',
    timeBefore = 'timeBefore',
    weekday = 'weekday',
    activePlayersOnMap = 'activePlayersOnMap',
    hasActiveBlessing = 'hasActiveBlessing',
}
